services:
  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shopdb
    volumes:
      - master_data:/var/lib/mysql
      - ./master-conf/my.cnf:/etc/mysql/conf.d/replication.cnf:ro
    ports:
      - "3307:3306"

  mysql-replica:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - replica_data:/var/lib/mysql
      - ./replica-conf/my.cnf:/etc/mysql/conf.d/replication.cnf:ro
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master

volumes:
  master_data:
  replica_data:
